snakefile: Snakefile
cores: 3
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 3
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 400                              #Use at most N CPU cluster/cloud jobs in parallel.
# Example resource configuration
default-resources:
   - runtime=100
   - mem_mb=6000
   - disk_mb=1000000
# # set-threads: map rule names to threads
set-threads:
   - single_core_rule=1
   - multi_core_rule=10
# # set-resources: map rule names to resources in general
set-resources:
   - high_memory_rule:mem_mb=12000
   - long_running_rule:runtime=1200
